model:
  num_layers: 4
  num_heads: 8
  embedding_dim: 256

training:
  epochs: 5
  batch_size: 2
  learning_rate: 0.0005
  data_path: "data/seed_conversations.jsonl"
  tokenizer_path: "tokenizer.json"
  output_path: "model.safetensors"
  log_dir: "logs/"

